### ISSUE TITLE
after upip.install("esp32ecp5")  an error is reported when doing import ecp5 

### ISSUE THREAD

**Issue by janrinze** [emard/ulx3s-bin#8]
Since upgrading the esp32 with :  import upip;upip.install("esp32ecp5")

I get the following error:

Welcome to MicroPython!                                                                                                                   
Password:                                                                                                                                             
WebREPL connected                                                                                                                                     
>>> import ecp5                                                                                                                                       
Traceback (most recent call last):                                                                                                                    
  File "<stdin>", line 1, in <module>                                                                                                                 
  File "ecp5.py", line 8, in <module>                                                                                                                 
ImportError: cannot import name SoftSPI                                                                                                               
>>> 

Somehow SoftSPI has disappeared.
Do other people have similar issues?

**Comment by emard** [comment]
This error is probably from micropython v1.12

Recommended is (still) micropython 1.14 IDF3. IDF4 works but leaves
less RAM free
version 1.12 doesn't have SoftSPI but it would work with SPI(-1, instead of
SoftSPI(
versions newer than 1.14 are ok for SoftSPI and SPI but they crash at unmounting SD
card.

SD unmount crash bug is reported to micropython but not yet solved

**Comment by janrinze** [comment]
Thanks for the swift reply!
Flashing with esp32-idf3-20210202-v1.14.bin fixed it. (need to reconfigure everything afterwards.)
